# Generated by Django 6.0.4 on 2026-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='body',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='news.article'),
        ),
    ]
