# Generated by Django 6.0.4 on 2026-06-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsletter_body_newsletter_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='independent_articles',
            field=models.ManyToManyField(blank=True, related_name='independent_authors', to='news.article'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='independent_newsletters',
            field=models.ManyToManyField(blank=True, related_name='independent_newsletters', to='news.newsletter'),
        ),
    ]
